# You are given two strings s and t.

# String t is generated by random shuffling string s and then add one more letter at a random position.

# Return the letter that was added to t.

class P389_FindtheDifference(object):
    def findTheDifference(self, s, t):
        check = s
        checked = t
        check_List = list(s)
        checked_List = list(t) # convert strings to char arrays
        
        for x in range(len(check_List)):
            for y in range(len(checked_List)):
                if (check_List[x] == checked_List[y]):
                  check_List[x] = " "
                  checked_List[y] = " "        # mark "found" characters with empty string

        added = " "
        for z in checked_List:
            if (z != " "): 
                 added = z  # added will contain the extra char in t

        return added

# below is a more efficient solution (linear runtime)
        
# class Solution(object):
#    def findTheDifference(self, s, t):
#        check_List = list(s)
#        checked_List = list(t)  # Convert strings to char arrays
#
#        # Create a dictionary to store character counts for s
#        char_count = {}
#        
#        for char in check_List:
#            if char in char_count:
#                char_count[char] += 1
#            else:
#                char_count[char] = 1
#
#        # Iterate through t and decrement counts in the dictionary
#        for char in checked_List:
#            if char in char_count and char_count[char] > 0:
#                char_count[char] -= 1
#            else:
#                return char  # This is the added character
